name: Texdora
description: Build your LaTeX documents with texlive.

runs:
  using: 'docker'
  image: 'docker://ghcr.io/benjaminboboul/texdora:2.0.1' # x-release-please-version
  entrypoint: /usr/bin/make
  args:
    - 'document.pdf'