name: texdora-build
description: Build your LaTeX documents with texlive.

branding:
  icon: 'book-open'
  color: 'white'

inputs:
  target:
    description: >
      Makefile target used to generate your LaTeX documents (default: target.pdf) 
    required: false
    type: string
    default: 'target.pdf'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/bugbundle/texdora:v4.0.3' # x-release-please-version
  entrypoint: /usr/bin/make
  args:
    - "${{ inputs.target }}"
